spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: dummy-service
          uri: lb://DUMMY-SERVICE
          predicates:
            - Path=/dummy/**
          filters:
            - RemoveRequestHeader=Cookie
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 7
                key-resolver: "#{@userKeyResolver}"
